version: '3'
services:
  app1:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
